### ISSUE TITLE
Issue after ctbenv/bin/cryptotrackerbot token

### ISSUE THREAD

**Issue by ghost** [91DarioDev/CryptoTrackerBot#4]
Hello!

I am getting the following error right after running `ctbenv/bin/cryptotrackerbot token` - see below:

> ctbenv/bin/cryptotrackerbot token
> /home/fs/ctbenv/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py:106: MatplotlibDeprecationWarning: The finance module has been deprecated in mpl 2.0 and will be removed in mpl 2.2. Please use the module mpl_finance instead.
>   warnings.warn(message, mplDeprecation, stacklevel=1)
> 
> running...
> Traceback (most recent call last):
>   File "ctbenv/bin/cryptotrackerbot", line 11, in <module>
>     load_entry_point('cryptotrackerbot==1', 'console_scripts', 'cryptotrackerbot')()
>   File "/home/fs/ctbenv/lib/python3.6/site-packages/cryptotrackerbot/__main__.py", line 47, in main
>     updater = Updater(token=bot_token, workers=10)
>   File "/home/fs/ctbenv/lib/python3.6/site-packages/telegram/ext/updater.py", line 122, in __init__
>     self.bot = Bot(token, base_url, request=self._request)
>   File "/home/fs/ctbenv/lib/python3.6/site-packages/telegram/bot.py", line 108, in __init__
>     self.token = self._validate_token(token)
>   File "/home/fs/ctbenv/lib/python3.6/site-packages/telegram/bot.py", line 134, in _validate_token
>     raise InvalidToken()
> telegram.error.InvalidToken: Invalid token
> 
> 
>

**Comment by 91DarioDev** [comment]
@c7oud  sorry for being late to answer. by the way the error is very clear: the token is invalid. maybe you wrote it wrong or it has been expired. can you check it?

**Comment by 91DarioDev** [comment]
of course you have to replace "token" with the token that [botfather](https://t.me/botfather) gives you. you don't have to type "token"
